version: 0.2

phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - npm install
            - echo Installing angular CLI...
            - npm install -g @angular/cli
    build:
        commands:
            - echo Production build started on `date`
            - ng build --prod
            - echo Build completed on `date`
    post_build:
         commands:
            - echo saving production build to S3
            - aws s3 cp dist s3://chasqui-test --recursive
            - echo finish saving production build to S3
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes